version: '3.8'

services:
#   mongo:
#     image: mongo:latest
#     container_name: mongo
#     networks:
#       - mern-net
#     ports:
#       - "27017:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: root

  # backend:
  #   build: ./server
  #   container_name: server
  #   networks:
  #     - mern-net
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mongo
  #   environment:
  #     - MONGO_URI=mongodb://root:root@mongo:27017/mern-app?authSource=admin

  frontend:
    build: ./front-end
    container_name: client
    networks:
      - mern-net
    ports:
      - "3000:3000"
    # depends_on:
    #   - backend
    # environment:
    #   - REACT_APP_PUBLIC_FOLDERI=http://localhost:5000/images/

networks:
  mern-net:
    driver: bridge